### ISSUE TITLE
Wandb training gets stuck

### ISSUE THREAD

**Issue by 131413ljk** [JoeYing1019/MMSD2.0#2]
After the 10th epoch of training, wandb will get stuck and keep showing wandb: - 0.000 MB of 0.010 MB uploaded (0.000 MB deduped)？

![训练日志](https://github.com/user-attachments/assets/fd041359-3b5a-44e6-8e12-70a038c40c01)

**Comment by JoeYing1019** [comment]
This is caused by network issues or wandb itself (https://github.com/wandb/wandb/issues/4929). You can use the offline mode of wandb, or consider adopting other log-tracking tools.
