### ISSUE TITLE
About the selection of indicators

### ISSUE THREAD

**Issue by Aichiniuroumian** [JoeYing1019/MMSD2.0#3]
Hi, @JoeYing1019 , this is really an amazing work, I was reproducing your code and I got two sets of values, macro and micro, but there is no indication in your paper which set of values you ended up with, can you help me out? Thank you very much!

**Comment by JoeYing1019** [comment]
Thank you for your interest in our work. The results reported in the paper are all micro values shown in wandb, which correspond to the "binary" average in scikit-learn.
